# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Qn963_4Nn5CzDFqmbBkz59SWlGJgGhe
"""

try:
    import streamlit as st
except ImportError:
    # If streamlit is not found, install it
    !pip install streamlit -qq
    # Try importing again after installation
    import streamlit as st

import pandas as pd
import joblib

# =====================================================
# Load trained model and preprocessing objects
# =====================================================
model = joblib.load("best_svm.pkl")          # Change if another model is best
symmetric = joblib.load("scaler.pkl")
label_encoder = joblib.load("label_encoder.pkl")
feature_columns = joblib.load("feature_columns.pkl")   # Save this from notebook

# =====================================================
# Page Configuration
# =====================================================
st.set_page_config(
    page_title="Obesity Level Prediction",
    page_icon="🏥",
    layout="centered"
)

st.title("🏥 Obesity Level Prediction System")
st.write("Enter your health and lifestyle information below to predict your obesity level.")

st.divider()

# =====================================================
# Personal Information
# =====================================================
st.header("👤 Personal Information")

gender = st.selectbox("Gender", ["Female", "Male"])
age = st.number_input("Age", 1, 100, 25)
height = st.number_input("Height (m)", 1.00, 2.50, 1.70, step=0.01)
weight = st.number_input("Weight (kg)", 20.0, 250.0, 70.0)

# =====================================================
# Lifestyle Habits
# =====================================================
st.header("🍎 Lifestyle Habits")

family_history = st.selectbox(
    "Family History with Overweight",
    ["yes", "no"]
)

favc = st.selectbox(
    "Frequent High Calorie Food Consumption",
    ["yes", "no"]
)

fcvc = st.slider(
    "Vegetable Consumption (FCVC)",
    1.0, 3.0, 2.0, 0.5
)

ncp = st.slider(
    "Main Meals per Day (NCP)",
    1.0, 4.0, 3.0, 0.5
)

caec = st.selectbox(
    "Snacking Between Meals",
    ["No", "Sometimes", "Frequently", "Always"]
)

smoke = st.selectbox(
    "Smoking",
    ["yes", "no"]
)

ch2o = st.slider(
    "Daily Water Intake (CH2O)",
    1.0, 3.0, 2.0, 0.5
)

scc = st.selectbox(
    "Calories Consumption Monitoring",
    ["yes", "no"]
)

faf = st.slider(
    "Physical Activity Frequency (FAF)",
    0.0, 3.0, 1.0, 0.5
)

tue = st.slider(
    "Technology Usage Time (TUE)",
    0.0, 2.0, 1.0, 0.5
)

calc = st.selectbox(
    "Alcohol Consumption (CALC)",
    ["No", "Sometimes", "Frequently", "Always"]
)

mtrans = st.selectbox(
    "Transportation",
    [
        "Walking",
        "Bike",
        "Motorbike",
        "Public_Transportation",
        "Automobile"
    ]
)

st.divider()

# =====================================================
# Prediction Button
# =====================================================
if st.button("🔍 Predict Obesity Level"):

    # Raw input dataframe
    input_df = pd.DataFrame({

        'Gender':[gender],
        'Age':[age],
        'Height':[height],
        'Weight':[weight],
        'family_history_with_overweight':[family_history],
        'FAVC':[favc],
        'FCVC':[fcvc],
        'NCP':[ncp],
        'CAEC':[caec],
        'SMOKE':[smoke],
        'CH2O':[ch2o],
        'SCC':[scc],
        'FAF':[faf],
        'TUE':[tue],
        'CALC':[calc],
        'MTRANS':[mtrans]

    })

    # One-Hot Encoding
    input_encoded = pd.get_dummies(input_df)

    # Match training columns
    input_encoded = input_encoded.reindex(
        columns=feature_columns,
        fill_value=0
    )

    # Scale
    input_scaled = symmetric.transform(input_encoded)

    # Prediction
    prediction = model.predict(input_scaled)

    obesity_level = label_encoder.inverse_transform(prediction)

    st.success(f"🎯 Predicted Obesity Level: **{obesity_level[0]}**")